@startmindmap
title Mapa Mental de Escolhas

* .

** Material único
*** Quantidade
**** Tipo do material
***** Liso
****** Cor
***** Rajado
****** Cores
***** Metálico
** Material variado
*** Tipo do material
@endmindmap
