version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: necklace_generator_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:create db:migrate && rails server -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/necklace-generator
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: necklace_generator_development

  db:
    image: mysql:8.0
    container_name: necklace_generator_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: necklace_generator_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
